// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module brenner_accel_brenner_accel_Pipeline_row_loop_col_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_axis_video_TVALID,
        mul_ln10,
        width,
        s_axis_video_TDATA,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        sum_diff_sq_out,
        sum_diff_sq_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_axis_video_TVALID;
input  [61:0] mul_ln10;
input  [31:0] width;
input  [7:0] s_axis_video_TDATA;
output   s_axis_video_TREADY;
input  [0:0] s_axis_video_TKEEP;
input  [0:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [63:0] sum_diff_sq_out;
output   sum_diff_sq_out_ap_vld;

reg ap_idle;
reg s_axis_video_TREADY;
reg sum_diff_sq_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln31_reg_337;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln31_fu_155_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_axis_video_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln44_fu_196_p2;
reg   [0:0] icmp_ln44_reg_341;
reg   [63:0] sum_diff_sq_fu_70;
wire   [63:0] sum_diff_sq_2_fu_265_p3;
reg    ap_block_pp0_stage0_11001_grp1;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [30:0] x_fu_74;
wire   [30:0] x_1_fu_202_p2;
wire    ap_block_pp0_stage0;
reg   [7:0] empty_fu_78;
reg   [61:0] indvar_flatten_fu_82;
wire   [61:0] add_ln31_fu_172_p2;
reg   [7:0] empty_15_fu_86;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [31:0] zext_ln32_fu_163_p1;
wire   [0:0] icmp_ln32_fu_167_p2;
wire   [30:0] select_ln25_fu_178_p3;
wire   [29:0] tmp_fu_186_p4;
wire   [8:0] zext_ln45_fu_231_p1;
wire   [8:0] zext_ln45_1_fu_235_p1;
wire   [8:0] diff_fu_239_p2;
wire  signed [8:0] mul_ln46_fu_249_p0;
wire  signed [17:0] sext_ln45_fu_245_p1;
wire  signed [8:0] mul_ln46_fu_249_p1;
wire   [17:0] mul_ln46_fu_249_p2;
wire  signed [63:0] sext_ln46_fu_255_p1;
wire   [63:0] sum_diff_sq_1_fu_259_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 sum_diff_sq_fu_70 = 64'd0;
#0 x_fu_74 = 31'd0;
#0 empty_fu_78 = 8'd0;
#0 indvar_flatten_fu_82 = 62'd0;
#0 empty_15_fu_86 = 8'd0;
#0 ap_done_reg = 1'b0;
end

brenner_accel_mul_9s_9s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 18 ))
mul_9s_9s_18_1_1_U1(
    .din0(mul_ln46_fu_249_p0),
    .din1(mul_ln46_fu_249_p1),
    .dout(mul_ln46_fu_249_p2)
);

brenner_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_15_fu_86 <= 8'd0;
        end else if (((icmp_ln31_reg_337 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            empty_15_fu_86 <= s_axis_video_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_fu_78 <= 8'd0;
        end else if (((icmp_ln31_reg_337 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            empty_fu_78 <= empty_15_fu_86;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 62'd0;
        end else if (((icmp_ln31_fu_155_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln31_fu_172_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            sum_diff_sq_fu_70 <= 64'd0;
        end else if (((icmp_ln31_reg_337 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            sum_diff_sq_fu_70 <= sum_diff_sq_2_fu_265_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_74 <= 31'd0;
        end else if (((icmp_ln31_fu_155_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_fu_74 <= x_1_fu_202_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln31_reg_337 <= icmp_ln31_fu_155_p2;
        icmp_ln44_reg_341 <= icmp_ln44_fu_196_p2;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_155_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (icmp_ln31_reg_337 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_axis_video_TDATA_blk_n = s_axis_video_TVALID;
    end else begin
        s_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln31_reg_337 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s_axis_video_TREADY = 1'b1;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (icmp_ln31_reg_337 == 1'd1) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        sum_diff_sq_out_ap_vld = 1'b1;
    end else begin
        sum_diff_sq_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_fu_172_p2 = (indvar_flatten_fu_82 + 62'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((icmp_ln31_reg_337 == 1'd0) & (s_axis_video_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign diff_fu_239_p2 = (zext_ln45_fu_231_p1 - zext_ln45_1_fu_235_p1);

assign icmp_ln31_fu_155_p2 = ((indvar_flatten_fu_82 == mul_ln10) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_167_p2 = (($signed(zext_ln32_fu_163_p1) < $signed(width)) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_196_p2 = ((tmp_fu_186_p4 != 30'd0) ? 1'b1 : 1'b0);

assign mul_ln46_fu_249_p0 = sext_ln45_fu_245_p1;

assign mul_ln46_fu_249_p1 = sext_ln45_fu_245_p1;

assign select_ln25_fu_178_p3 = ((icmp_ln32_fu_167_p2[0:0] == 1'b1) ? x_fu_74 : 31'd0);

assign sext_ln45_fu_245_p1 = $signed(diff_fu_239_p2);

assign sext_ln46_fu_255_p1 = $signed(mul_ln46_fu_249_p2);

assign sum_diff_sq_1_fu_259_p2 = ($signed(sum_diff_sq_fu_70) + $signed(sext_ln46_fu_255_p1));

assign sum_diff_sq_2_fu_265_p3 = ((icmp_ln44_reg_341[0:0] == 1'b1) ? sum_diff_sq_1_fu_259_p2 : sum_diff_sq_fu_70);

assign sum_diff_sq_out = sum_diff_sq_fu_70;

assign tmp_fu_186_p4 = {{select_ln25_fu_178_p3[30:1]}};

assign x_1_fu_202_p2 = (select_ln25_fu_178_p3 + 31'd1);

assign zext_ln32_fu_163_p1 = x_fu_74;

assign zext_ln45_1_fu_235_p1 = empty_fu_78;

assign zext_ln45_fu_231_p1 = s_axis_video_TDATA;

endmodule //brenner_accel_brenner_accel_Pipeline_row_loop_col_loop
