# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0_3/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0_2/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_0_3/design_1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_2_0_2/design_1_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_2_0 || ORIG_REF_NAME==design_1_clk_wiz_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psr_100m_0_2/design_1_psr_100m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_psr_100m_0 || ORIG_REF_NAME==design_1_psr_100m_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psr_125m_0_2/design_1_psr_125m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_psr_125m_0 || ORIG_REF_NAME==design_1_psr_125m_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psr_156m_0_2/design_1_psr_156m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_psr_156m_0 || ORIG_REF_NAME==design_1_psr_156m_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_psr_200m_0_2/design_1_psr_200m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_psr_200m_0 || ORIG_REF_NAME==design_1_psr_200m_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0_3/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_clk_conv_0_0_1/design_1_axi_clk_conv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_clk_conv_0_0 || ORIG_REF_NAME==design_1_axi_clk_conv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gige_dual_speed_top_0_0_2/design_1_gige_dual_speed_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_gige_dual_speed_top_0_0 || ORIG_REF_NAME==design_1_gige_dual_speed_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0_3/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_0_2/design_1_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_0 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_brenner_accel_0_0_3/design_1_brenner_accel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_brenner_accel_0_0 || ORIG_REF_NAME==design_1_brenner_accel_0_0} -quiet] -quiet

# XDC: d:/Projects/FPGA_projects/GigE_HLS_Test/GigE_HLS_Test.gen/sources_1/bd/design_1/design_1_ooc.xdc
